### ISSUE TITLE
Use of php ShortTags 

### ISSUE THREAD

**Issue by cap60552** [ndlibersa/auth#10]
The use of the PHP short tag <?=   only works in php versions 5.4 and up.   

Please either list php 5.4 as a requirement, or revert to using full <?php  tags.

**Comment by remocrevo** [comment]
@cap60552 Thanks for posting your concern.  We've previously discussed this issue and decided that PHP version 5.4+ is assumed because 5.3 (and 5.4 now) is past end-of-life (see http://php.net/supported-versions.php).

Our previous discussion can be found here:
https://github.com/ndlibersa/auth/pull/3#issuecomment-125600837
